### ISSUE TITLE
iOS10 minimum deployment target

### ISSUE THREAD

**Issue by lukewakeford** [pusher/push-notifications-swift#43]
Hey, I have a project that supports back to iOS9.

How can I use pusher push notifications with this project without updating my projects minimum deployment target?

**Comment by lukabratos** [comment]
Hi @lukewakeford 

Minimum iOS version that we support is iOS 10.0
We made this decision because the percentage of the users using version less than 10.0 is very little, according to:
* [Apple, around 7%](https://developer.apple.com/support/app-store/).
* [Apteligent, around 5%](https://data.apteligent.com/ios/)

I'm aware that sometimes it's very difficult to set the minimum deployment target to a newer version because of the business requirements, but I would definitely recommend to do that.

Luka

**Comment by lukewakeford** [comment]
Thanks for the response.

Unfortunately this meant that we used another solution.

Take it easy.
